Our data needs to be cleaned before being used in our Power BI dashboards. These Python scripts will be implemented in Power BI, and our data will run through them before being displayed.

## **NOPD Misconduct Complaints**

In [ ]:
import pandas as pd
import numpy as np
from google.colab import files

In [ ]:
df = pd.read_csv('NOPD_Misconduct_Complaints.csv');
df.head()

,Incident Type,Complaint Tracking Number,Date Complaint Occurred,Date Complaint Received by NOPD (PIB),Date Complaint Investigation Complete,Complaint classification,Investigation status,Disposition,Bureau of Complainant,Division of Complainant,...,Rule Violation,Paragraph Violation,Unique Officer Allegation ID,Officer Race Ethnicity,Officer Gender,Officer Age,Officer years of service,Complainant Gender,Complainant Ethnicity,Complainant Age
0,Public Initiated,2016-0001-P,2016-01-01,2016-01-01,2016-07-21,DI-1,Completed,Unfounded,NaN,8th District,...,RULE 3: PROF CONDUCT,PARAGRAPH 01 - Professionalism,30664.0,NaN,NaN,NaN,NaN,Male,Black,NaN
1,Public Initiated,2016-0002-P,2016-01-02,2016-01-01,2016-08-03,DI-1,Completed,Exonerated,FOB - Field Operations Bureau,7th District,...,RULE 4: PERF OF DUTY,PARAGRAPH 04 - NEGLECT OF DUTY,30667.0,Black,Male,60,NaN,Female,White,NaN
2,Public Initiated,2016-0002-P,2016-01-02,2016-01-01,2016-08-03,DI-1,Completed,Exonerated,FOB - Field Operations Bureau,7th District,...,RULE 4: PERF OF DUTY,PARAGRAPH 04 - NEGLECT OF DUTY,30669.0,Black,Male,44,NaN,Female,White,NaN
3,Public Initiated,2016-0009-P,2016-01-04,2016-01-04,2017-03-20,DI-1,Completed,Unfounded,FOB - Field Operations Bureau,8th District,...,RULE 2: MORAL CONDUCT,PARAGRAPH 01 - ADHERENCE TO LAW,30671.0,White,Male,30,NaN,NaN,NaN,NaN
4,Public Initiated,2016-0006-P,2016-12-30,2016-01-04,2016-07-25,DI-1,Completed,Exonerated,FOB - Field Operations Bureau,Command Staff,...,RULE 4: PERF OF DUTY,PARAGRAPH 02 - INSTRUCTIONS FROM AUTHORITATIVE...,30674.0,Black,Male,54,NaN,Female,Black,50.0

In [ ]:
# Remove spelling inconsistencies in complainant gender
pd.unique(df['Complainant Gender'])

array(['Male', 'Female', nan, 'Sex-Unk', 'f', 'female', 'FEMALE', 'F',
       'M', 'm', 'femal', 'femaale', 'Unkown', 'Female10', 'unknown'],
      dtype=object)

In [ ]:
df['Complainant Gender'] = df['Complainant Gender'].replace(dict.fromkeys(['f', 'female', 'FEMALE', 'F', 'femal', 'femaale', 'Female10'], 'Female'))
df['Complainant Gender'] = df['Complainant Gender'].replace(dict.fromkeys(['M', 'm'], 'Male'))
df['Complainant Gender'] = df['Complainant Gender'].replace(dict.fromkeys(['Sex-Unk', 'Unkown', 'unknown'], np.nan))
pd.unique(df['Complainant Gender'])

array(['Male', 'Female', nan], dtype=object)

In [ ]:
# Remove spelling inconsistencies in complainant ethnicity
pd.unique(df['Complainant Ethnicity'])

array(['Black', 'White', nan, 'Asian', 'Race-Unknown', 'Hispanic', 'b',
       'white', 'Indian', 'w', 'BLACK', 'B', 'W', 'black', 'Unknown',
       'Unkown', 'unknown'], dtype=object)

In [ ]:
df['Complainant Ethnicity'] = df['Complainant Ethnicity'].replace(dict.fromkeys(['b', 'BLACK', 'B', 'black'], 'Black'))
df['Complainant Ethnicity'] = df['Complainant Ethnicity'].replace(dict.fromkeys(['white', 'w', 'W'], 'White'))
df['Complainant Ethnicity'] = df['Complainant Ethnicity'].replace(dict.fromkeys(['Race-Unknown', 'Unknown', 'Unkown', 'unknown'], np.nan))
pd.unique(df['Complainant Ethnicity'])

array(['Black', 'White', nan, 'Asian', 'Hispanic', 'Indian'], dtype=object)

In [ ]:
# Remove erroneous values from officer ethnicity
pd.unique(df['Officer Race Ethnicity'])

array([nan, 'Black', 'White', 'Hispanic', 'Not Specified',
       'Asian/Pacific Islander', 'American Indian/Alaska Native',
       'Not Applicable (Non-U.S.)', ' Giving Anything of Value',
       'PARAGRAPH 01 - Professionalism'], dtype=object)

In [ ]:
df['Officer Race Ethnicity'] = df['Officer Race Ethnicity'].replace(dict.fromkeys(['Not Specified', 'Not Applicable (Non-U.S.)',
                               ' Giving Anything of Value', 'PARAGRAPH 01 - Professionalism'], np.nan))
pd.unique(df['Officer Race Ethnicity'])

array([nan, 'Black', 'White', 'Hispanic', 'Asian/Pacific Islander',
       'American Indian/Alaska Native'], dtype=object)

In [ ]:
# Remove erroneous values from officer gender
pd.unique(df['Officer Gender'])

array([nan, 'Male', 'Female', 'N', 'Black', 'White'], dtype=object)

In [ ]:
df['Officer Gender'] = df['Officer Gender'].replace(dict.fromkeys(['N', 'Black', 'White'], np.nan))
pd.unique(df['Officer Gender'])

array([nan, 'Male', 'Female'], dtype=object)

In [ ]:
# Clean 'Rule Violation' String
pd.unique(df['Rule Violation'])

array(['RULE 3: PROF CONDUCT', 'RULE 4: PERF OF DUTY',
       'RULE 2: MORAL CONDUCT', 'RULE 7: DEPT PROPERTY',
       'NO VIOLATION OBSERVED', 'NO ALLIGATIONS ASSIGNED AT THIS TIME',
       'RULE 6: OFFICIAL INFO', nan, 'RULE 5: REST ACTIVITIES',
       'RULE 1: OPERATION MANUALS', 'POLICY', 'Unknown Shift Hours'],
      dtype=object)

In [ ]:
df['Rule Violation'] = df['Rule Violation'].str.split(':', 1).str[1].str.strip().str.title()
pd.unique(df['Rule Violation'])

array(['Prof Conduct', 'Perf Of Duty', 'Moral Conduct', 'Dept Property',
       nan, 'Official Info', 'Rest Activities', 'Operation Manuals'],
      dtype=object)

In [ ]:
# Clean 'Paragraph Violation' string
pd.unique(df['Paragraph Violation'])

array(['PARAGRAPH 01 - Professionalism', 'PARAGRAPH 04 - NEGLECT OF DUTY',
       'PARAGRAPH 01 - ADHERENCE TO LAW',
       'PARAGRAPH 02 - INSTRUCTIONS FROM AUTHORITATIVE SOURCE',
       'PARAGRAPH 03 - CLEANLINESS OF DEPARTMENT EQUIPMENT', nan,
       'PARAGRAPH 08 - FAILURE TO REPORT MISCONDUCT',
       'PARAGRAPH 04 - DISCRIMINATION',
       'PARAGRAPH 01 - REPORTING FOR DUTY',
       'PARAGRAPH 02 - FALSE OR INACCURATE REPORTS',
       'PARAGRAPH 05 - VERBAL INTIMIDATION',
       'PARAGRAPH 08 - Use of Alchohol/Drugs On Duty',
       'PARAGRAPH 03 - DEVOTING ENTIRE TIME TO DUTY',
       'PARAGRAPH 02 - COURTESY',
       'PARAGRAPH 03 - HONESTY AND TRUTHFULNESS',
       'PARAGRAPH 02 -Abuse of Position',
       'PARAGRAPH 07 - Use of Drugs/Substance Abuse Testing',
       'PARAGRAPH 11 - INTERFERING WITH INVESTIGATIONS',
       'PARAGRAPH 06 - UNAUTHORIZED FORCE',
       'PARAGRAPH 07 - ACTING IMPARTIALLY', 'PARAGRAPH 02 - ASSOCIATIONS',
       'PARAGRAPH 01 - USE OF DEPARTMENT EQUIPMENT',
       'PARAGRAPH 13 - Social Networking...etc.',
       'PAPRGRAPH 1: RULES OF PROCEDURES',
       'PARAGRAPH 07 - LEAVING CITY ON DUTY',
       'PARAGRAPH 01 - FICTITIOUS ILLNESS OR INJURY',
       'PARAGRAPH 11 - Use Of Tabacco',
       'PARAGRAPH 03 - Neatness & Attire',
       '446.3.1 Digital Mobil Video Audio Recording',
       'PARAGRAPH 06 - LEAVING ASSIGNED AREA',
       'PARAGRAPH 12 - RETALIATION', 'PARAGRAPH 06 - AUTHORIZED FORCE',
       'PARAGRAPH 03 - VISITING PROHIBITED ESTABLISHMENTS',
       'PARAGRAPH 01 - SECURITY OF RECORDS',
       'PARAGRAPH 02 - AUTHORIZED OPERATOR OF DEPARTMENT EQUIPMENT',
       'PARAGRAPH 09 - Use of Alchohol/Drugs Off-Duty',
       'PARAGRAPH 09 - CRIMINAL PROCEEDING AGAINST MEMBER(S)',
       'PARAGRAPH 05 - CEASING TO PERFORM BEFORE END OF SHIFT',
       'PARAGRAPH 06 - ACTING IN CIVIL MATTERS',
       'PARAGRAPH 04 - Accepting',
       'PARAGRAPH 10 - TESTIFYING ON BEHALF OF DEFENDENT(S)',
       'RULE 3: PROF CONDUCT', 'PARAGRAPH 08 - CIVIL SUITS BY MEMBER'],
      dtype=object)

In [ ]:
df['Paragraph Violation'] = df['Paragraph Violation'].str.split('-', 1).str[1].str.strip().str.title()
pd.unique(df['Paragraph Violation'])

array(['Professionalism', 'Neglect Of Duty', 'Adherence To Law',
       'Instructions From Authoritative Source',
       'Cleanliness Of Department Equipment', nan,
       'Failure To Report Misconduct', 'Discrimination',
       'Reporting For Duty', 'False Or Inaccurate Reports',
       'Verbal Intimidation', 'Use Of Alchohol/Drugs On Duty',
       'Devoting Entire Time To Duty', 'Courtesy',
       'Honesty And Truthfulness', 'Abuse Of Position',
       'Use Of Drugs/Substance Abuse Testing',
       'Interfering With Investigations', 'Unauthorized Force',
       'Acting Impartially', 'Associations',
       'Use Of Department Equipment', 'Social Networking...Etc.',
       'Leaving City On Duty', 'Fictitious Illness Or Injury',
       'Use Of Tabacco', 'Neatness & Attire', 'Leaving Assigned Area',
       'Retaliation', 'Authorized Force',
       'Visiting Prohibited Establishments', 'Security Of Records',
       'Authorized Operator Of Department Equipment',
       'Use Of Alchohol/Drugs Off-Duty',
       'Criminal Proceeding Against Member(S)',
       'Ceasing To Perform Before End Of Shift',
       'Acting In Civil Matters', 'Accepting',
       'Testifying On Behalf Of Defendent(S)', 'Civil Suits By Member'],
      dtype=object)

In [ ]:
display(df)

,Incident Type,Complaint Tracking Number,Date Complaint Occurred,Date Complaint Received by NOPD (PIB),Date Complaint Investigation Complete,Complaint classification,Investigation status,Disposition,Bureau of Complainant,Division of Complainant,...,Rule Violation,Paragraph Violation,Unique Officer Allegation ID,Officer Race Ethnicity,Officer Gender,Officer Age,Officer years of service,Complainant Gender,Complainant Ethnicity,Complainant Age
0,Public Initiated,2016-0001-P,2016-01-01,2016-01-01,2016-07-21,DI-1,Completed,Unfounded,NaN,8th District,...,RULE 3: PROF CONDUCT,PARAGRAPH 01 - Professionalism,30664.0,NaN,NaN,NaN,NaN,Male,Black,NaN
1,Public Initiated,2016-0002-P,2016-01-02,2016-01-01,2016-08-03,DI-1,Completed,Exonerated,FOB - Field Operations Bureau,7th District,...,RULE 4: PERF OF DUTY,PARAGRAPH 04 - NEGLECT OF DUTY,30667.0,Black,Male,60,NaN,Female,White,NaN
2,Public Initiated,2016-0002-P,2016-01-02,2016-01-01,2016-08-03,DI-1,Completed,Exonerated,FOB - Field Operations Bureau,7th District,...,RULE 4: PERF OF DUTY,PARAGRAPH 04 - NEGLECT OF DUTY,30669.0,Black,Male,44,NaN,Female,White,NaN
3,Public Initiated,2016-0009-P,2016-01-04,2016-01-04,2017-03-20,DI-1,Completed,Unfounded,FOB - Field Operations Bureau,8th District,...,RULE 2: MORAL CONDUCT,PARAGRAPH 01 - ADHERENCE TO LAW,30671.0,White,Male,30,NaN,NaN,NaN,NaN
4,Public Initiated,2016-0006-P,2016-12-30,2016-01-04,2016-07-25,DI-1,Completed,Exonerated,FOB - Field Operations Bureau,Command Staff,...,RULE 4: PERF OF DUTY,PARAGRAPH 02 - INSTRUCTIONS FROM AUTHORITATIVE...,30674.0,Black,Male,54,NaN,Female,Black,50.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7077,Public Initiated,2023-0103-P,2023-02-17,2023-02-28,NaN,DI-1,Initial,Pending,FOB - Field Operations Bureau,8th District,...,NaN,NaN,69057.0,Black,Male,45,NaN,Female,NaN,NaN
7078,Public Initiated,2023-0103-P,2023-02-17,2023-02-28,NaN,DI-1,Initial,Pending,FOB - Field Operations Bureau,8th District,...,NaN,NaN,69059.0,White,Female,28,NaN,Female,NaN,NaN
7079,Public Initiated,2023-0097-P,2023-02-23,2023-02-23,NaN,DI-1,Active,Pending,NaN,NaN,...,RULE 2: MORAL CONDUCT,PARAGRAPH 06 - UNAUTHORIZED FORCE,69063.0,NaN,NaN,NaN,NaN,Female,Black,22.0
7080,Rank Initiated,2023-0094-R,NaN,2023-02-23,NaN,NaN,Initial,Pending,FOB - Field Operations Bureau,1st District,...,NaN,NaN,69066.0,Black,Male,NaN,NaN,NaN,NaN,NaN
7081,Public Initiated,2023-0079,2023-02-16,2023-02-17,NaN,DI-1,Initial,Pending,FOB - Field Operations Bureau,1st District,...,RULE 4: PERF OF DUTY,PARAGRAPH 04 - NEGLECT OF DUTY,69068.0,White,Male,45,NaN,Female,Black,30.0

In [ ]:
df.to_csv('output.csv')
files.download('output.csv')

# **Traffic Camera Locations**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('Traffic_Camera.csv');
df.head()

,the_geom,OBJECTID,Site Id,Direction,Street
0,POINT (-90.041571603615 29.933958410642),194,NO134 / A_B,NB,1921 LB Landry Ave
1,POINT (-90.100510621211 29.974765417625),117,NO01,SB,N Carrollton Ave @ Canal St
2,POINT (-90.100859621264 29.974584417526),118,NO02,EB,Canal St @ S Carrollton Ave
3,POINT (-90.037996605841 30.010602427458),200,NO141 / A_B,WB,4642 Mirabeau Ave
4,POINT (-90.090543620515 30.02205242824),208,NO152 / A_B,SB,78 Spanish Fort Blvd

In [ ]:
# extract latitude and longitude coordinates
df['the_geom'] = df['the_geom'].apply(lambda st: st[st.find("(")+1:st.find(")")])
df['latitude'] = df['the_geom'].str.split(' ').str[0]
df['longitude'] = df['the_geom'].str.split(' ').str[1]

In [ ]:
# specify address
df['street'] = df['street'] + ', New Orleans, LA'
df.rename(columns = {'street':'Address'}, inplace = True)

In [ ]:
# add category
df['Category'] = 'Safety Camera'
df.head()

,the_geom,OBJECTID,Site Id,Direction,Street,latitude,longitude,category
0,-90.041571603615 29.933958410642,194,NO134 / A_B,NB,1921 LB Landry Ave,-90.041571603615,29.933958410642,camera
1,-90.100510621211 29.974765417625,117,NO01,SB,N Carrollton Ave @ Canal St,-90.100510621211,29.974765417625,camera
2,-90.100859621264 29.974584417526,118,NO02,EB,Canal St @ S Carrollton Ave,-90.100859621264,29.974584417526,camera
3,-90.037996605841 30.010602427458,200,NO141 / A_B,WB,4642 Mirabeau Ave,-90.037996605841,30.010602427458,camera
4,-90.090543620515 30.02205242824,208,NO152 / A_B,SB,78 Spanish Fort Blvd,-90.090543620515,30.02205242824,camera

# **Crime - Police Calls 2023**

In [ ]:
# extract lat/long coords
dataset['location'] = dataset['location'].apply(lambda st: st[st.find("(")+1:st.find(")")])
dataset['latitude'] = dataset['location'].str.split(' ').str[0]
dataset['longitude'] = dataset['location'].str.split(' ').str[1]

In [ ]:
# specify address
dataset['Address'] = dataset['block_address'] + ', New Orleans, LA'

In [ ]:
# add category
dataset['Category'] = 'Crime - ' + dataset['typetext']

# **311 OPCD Calls**

In [ ]:
# specify address
dataset['Address'] = dataset['final_address'] + ', New Orleans, LA'

In [ ]:
# add category
dataset['Category'] = 'Blight - ' + dataset['request_reason']

## **Stop and Search**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('Stop_and_Search.csv');
df.head()

,FieldInterviewID,NOPD_Item,EventDate,District,Zone,OfficerAssignment,StopDescription,ActionsTaken,VehicleYear,VehicleMake,...,SubjectWeight,SubjectEyeColor,SubjectHairColor,SubjectDriverLicState,CreatedDateTime,LastModifiedDateTime,Longitude,Latitude,Zip,BlockAddress
0,250403,G3013114,07/18/2014 11:13:00 AM,2,T,2nd District,TRAFFIC VIOLATION,Stop Results: Citation Issued;Subject Type: Dr...,2008.0,INFINITY,...,175.0,Blue,Blonde,LA,07/18/2014 11:19:33 AM,NaN,0.0,0.0,NaN,NaN
1,250404,G2296214,07/18/2014 10:06:00 AM,5,B,5th District,TRAFFIC VIOLATION,Stop Results: Physical Arrest;Subject Type: Dr...,2005.0,NISSAN,...,187.0,Brown,Black,LA,07/18/2014 11:31:30 AM,NaN,0.0,0.0,NaN,NaN
2,250405,G2299814,07/18/2014 10:51:00 AM,5,C,5th District,SUSPECT PERSON,Stop Results: Physical Arrest;Subject Type: Dr...,2005.0,NISSAN,...,187.0,Brown,Black,LA,07/18/2014 11:35:23 AM,NaN,0.0,0.0,NaN,NaN
3,250406,G2303114,07/18/2014 11:24:00 AM,3,R,3rd District,TRAFFIC VIOLATION,Stop Results: Citation Issued;Stop Results: Ph...,2005.0,FORD,...,215.0,Brown,Black,LA,07/18/2014 12:06:27 PM,07/18/2014 01:28:48 PM,0.0,0.0,NaN,NaN
4,250407,F2194814,07/17/2014 03:32:00 PM,3,J,3rd District,CALL FOR SERVICE,Stop Results: Physical Arrest;Subject Type: Pe...,NaN,NaN,...,150.0,Green,Brown,LA,07/18/2014 12:13:21 PM,NaN,0.0,0.0,NaN,NaN

In [ ]:
df = df[df['SubjectRace'].notna()]

In [ ]:
pd.unique(df['SubjectRace'])

array(['WHITE', 'BLACK', 'HISPANIC', 'UNKNOWN', 'ASIAN', 'AMER. IND.',
       'NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER'], dtype=object)

In [ ]:
df = df[df['StopDescription'].notna()]

In [ ]:
pd.unique(df['VehicleStyle'])

array(['FOUR DOOR', 'PICK UP', nan, 'SPORTS UTILITY', 'TWO DOOR',
       'MINIVAN', 'OTHER', 'FULL SIZE VAN', 'STATION WAGON',
       'CONVERTIBLE', 'COMMERICAL TRUCK', 'WATERCRAFT', 'MOTORCYLE',
       'RECREATION VEHICLE', 'AIRCRAFT'], dtype=object)

In [ ]:
display(df)

,FieldInterviewID,NOPD_Item,EventDate,District,Zone,OfficerAssignment,StopDescription,ActionsTaken,VehicleYear,VehicleMake,...,SubjectWeight,SubjectEyeColor,SubjectHairColor,SubjectDriverLicState,CreatedDateTime,LastModifiedDateTime,Longitude,Latitude,Zip,BlockAddress
0,250403,G3013114,07/18/2014 11:13:00 AM,2,T,2nd District,TRAFFIC VIOLATION,Stop Results: Citation Issued;Subject Type: Dr...,2008.0,INFINITY,...,175.0,Blue,Blonde,LA,07/18/2014 11:19:33 AM,NaN,0.000000,0.000000,NaN,NaN
1,250404,G2296214,07/18/2014 10:06:00 AM,5,B,5th District,TRAFFIC VIOLATION,Stop Results: Physical Arrest;Subject Type: Dr...,2005.0,NISSAN,...,187.0,Brown,Black,LA,07/18/2014 11:31:30 AM,NaN,0.000000,0.000000,NaN,NaN
2,250405,G2299814,07/18/2014 10:51:00 AM,5,C,5th District,SUSPECT PERSON,Stop Results: Physical Arrest;Subject Type: Dr...,2005.0,NISSAN,...,187.0,Brown,Black,LA,07/18/2014 11:35:23 AM,NaN,0.000000,0.000000,NaN,NaN
3,250406,G2303114,07/18/2014 11:24:00 AM,3,R,3rd District,TRAFFIC VIOLATION,Stop Results: Citation Issued;Stop Results: Ph...,2005.0,FORD,...,215.0,Brown,Black,LA,07/18/2014 12:06:27 PM,07/18/2014 01:28:48 PM,0.000000,0.000000,NaN,NaN
4,250407,F2194814,07/17/2014 03:32:00 PM,3,J,3rd District,CALL FOR SERVICE,Stop Results: Physical Arrest;Subject Type: Pe...,NaN,NaN,...,150.0,Green,Brown,LA,07/18/2014 12:13:21 PM,NaN,0.000000,0.000000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557221,31852,NaN,06/13/2010 01:27:00 AM,6,I,6th District,SUSPECT PERSON,NaN,NaN,NaN,...,160.0,Brown,Black,NaN,06/13/2010 02:24:10 AM,NaN,0.000000,0.000000,NaN,NaN
557222,527800,K2069719,11/15/2019 07:15:00 PM,8,C,8th District,TRAFFIC VIOLATION,Stop Results: Citation Issued;Subject Type: Dr...,2015.0,DODGE,...,150.0,Brown,Black,LA,11/15/2019 08:16:13 PM,NaN,-90.068256,29.954106,70130.0,Royal St & Iberville St
557223,527801,K2073919,11/15/2019 08:33:00 PM,4,D,4th District,CALL FOR SERVICE,Stop Results: Physical Arrest;Subject Type: Pe...,NaN,NaN,...,200.0,Brown,NaN,NaN,11/15/2019 08:52:06 PM,12/10/2019 03:00:04 PM,-90.010636,29.924552,70131.0,043XX Macarthur Blvd
557224,527802,K2077619,11/15/2019 08:54:00 PM,2,U,2nd District,TRAFFIC VIOLATION,Stop Results: Verbal Warning;Subject Type: Dri...,2018.0,HYUNDAI,...,210.0,Brown,Black,LA,11/15/2019 09:00:57 PM,NaN,-90.111273,29.960341,70125.0,078XX Forshey St
557225,527803,K2079919,11/15/2019 09:20:00 PM,3,D,3rd District,TRAFFIC VI,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.to_csv('cleandf.csv')
files.download('cleandf.csv')